### PR TITLE
jobs: Add a column for end time/duration

### PR DESCRIPTION
**Pull request by tahini**

### CODE REVIEW

**Comment by tahini** [comment]
It looks like this

Capture d’écran du 2023-12-18 14-07-00

I'm still waiting for suggestions to make this job list prettier, maybe the docker build list (but we don't see the duration)?

**Comment by greenscientist** [comment]
The docker build list for exmple only has a start time and a duration. 
out of a start_time, end_time and duration, you only really need 2. The other can be infered with the other. 
Personnally, I think the duration is the field that people are probably most interested in

**Review by kaligrafy — APPROVED** [review]

**Comment by tahini** [comment]
And that might be a problem too if the task has spent time in a pending state... this PR gives a duration from last updated_at to created_at, but we don't have a started_at field...

**Comment by tahini** [comment]
But adding a started_at is a bit more involving than this quick one...

**Comment by greenscientist** [comment]
So the current displayed duration might be a lie?  
I was under the impression that this PR looked too easy for what it was...

**Comment by tahini** [comment]
#815 needs to be fixed first so we can calculate the actual duration of the job execution and not just it's life

**Comment by tahini** [comment]
Actually, I can just put the end time in this PR for now, without fixing either #813 or #815. it gives an information to the user, without lying about anything. Would that be all right? @greenscientist ?

**Comment by greenscientist** [comment]
Yes, that would work well for the moment and give a good enough insight to the user

**Comment by tahini** [comment]
Only the end time is present now

**Review by greenscientist — APPROVED** [review]

**Pull request merged**
