### PR TITLE
Use node instead of babel-node for CLI commands

### PR DESCRIPTION
**Pull request by tahini**
Typescript compile in commonjs, which is directly understandable by the `node` command and does not need babel-node.

### CODE REVIEW

**Comment by kaligrafy** [comment]
It does not need a "type": "module" in the package.json file?

**Comment by tahini** [comment]
apparently not...

**Comment by tahini** [comment]
I think since it's commonjs, it does not need it. The type: module is for ES modules, which is not the case here.

**Comment by tahini** [comment]
From https://nodejs.org/api/packages.html

"If the nearest parent package.json lacks a "type" field, or contains "type": "commonjs", .js files are treated as [CommonJS](https://nodejs.org/api/modules.html).
"

**Comment by kaligrafy** [comment]
ok, fine!

**Review by kaligrafy — APPROVED** [review]

**Comment by greenscientist** [comment]
I imagine this reduce the list of dependencies?

**Comment by tahini** [comment]
> I imagine this reduce the list of dependencies?

Indeed I think we don't need any babel packages anymore! I'll keep the ones in webpack, as the babel-loader may be required for the client packages. But all other packages don't need it.

**Review by greenscientist — APPROVED** [review]
cool

**Pull request merged**
