### PR TITLE
trRouting: Prepare routes to support v2/route endpoint

### PR DESCRIPTION
**Pull request by tahini**

### CODE REVIEW

**Comment by greenscientist** [comment]
Do we really want to support the old code path??

**Comment by tahini** [comment]
For now yes, so we can slowly do small reviewable PRs instead of a huge one (I had started the big one and it's all or nothing, here we can do the route first and accessibility next).

**Comment by greenscientist** [comment]
If I understand this properly, we are adding a new Transition API which have a TrRouting version. Can't we just hide that behind the Transition API?

**Comment by tahini** [comment]
Oh yeah and the client was preparing the query string as a string instead of the server... which makes it much much harder to support v2 here.

**Review by greenscientist — APPROVED** [review]
ok, let's do this then

**Pull request merged**
