### PR TITLE
Move navigation buttons to top of panel and add margin at the bottom of lines collapsible

### PR DESCRIPTION
**Pull request by davidmurray**
For second commit, looks like this now:
image

### CODE REVIEW

**Review by kaligrafy — CHANGES_REQUESTED** [review]
Please remove the config.js file from commit. I approve the rest!

**Comment by davidmurray** [comment]
sorry i keep committing that! I'll add it to my gitignore 
Anyways I will rewrite this PR to make the buttons float in the header at all times. Will be much better

**Comment by davidmurray** [comment]
Ready for review @kaligrafy 

Here is what it does:
https://github.com/chairemobilite/transition/assets/545502/14a967b9-61f8-4de6-aee5-375216da2d89

**Comment by kaligrafy** [comment]
cool!

**Review by kaligrafy — APPROVED** [review]

**Pull request merged**
