### PR TITLE
Copy the json2capnp service from legacy

### PR DESCRIPTION
**Pull request by tahini**
Note that the cache path directory must now be part of the command line since it can't be deduced from .env anymore.

Depends on #432 so still a draft

### CODE REVIEW

**Comment by greenscientist** [comment]
Looks fine

**Comment by greenscientist** [comment]
There's no change to other part of the documentation with the command line change?

**Comment by tahini** [comment]
> There's no change to other part of the documentation with the command line change?

There's no documentation in this repo yet ;-)

**Review by greenscientist — APPROVED** [review]
Ok, Let's not forget to update it before comitting it then

**Pull request merged**
