### PR TITLE
dep: Upgrade the telemetry packages

### PR DESCRIPTION
**Pull request by tahini**
Fixes a few security issues

* @opentelemetry/api: 1.0.1 => 1.9.0
* @opentelemetry/core: 0.23.0 => 1.25.1
* @opentelemetry/exporter-collector-grpc is replaced with @opentelemetry/exporter-trace-otlp-grpc (see https://www.npmjs.com/package/@opentelemetry/exporter-trace-otlp-grpc)
* @opentelemetry/instrumentation: 0.23.0 => 0.52.1
* @opentelemetry/instrumentation-express: 0.23.0 => 0.40.1
* @opentelemetry/instrumentation-http: 0.23.0 => 0.52.1
* @opentelemetry/resources: 0.23.0 => 1.25.1
* @opentelemetry/node is replaced with @opentelemetry/sdk-trace-node (see https://www.npmjs.com/package/@opentelemetry/sdk-trace-node)
* @opentelemetry/tracing is replaced with @opentelemetry/sdk/trace/base (see https://www.npmjs.com/package/@opentelemetry/sdk-trace-base)

### CODE REVIEW

**Comment by tahini** [comment]
@greenscientist there is nothing in the code base that uses opentelemetry, so I can't make any of the required changes. The infra may need to be updated, with the changes of packages

**Comment by greenscientist** [comment]
Yeah, there's some impact. Discussing offline.

**Comment by greenscientist** [comment]
The docker build failure seems related to their side, I don't see any error in the log, it just seem to get stuck installing some package.

**Review by greenscientist — APPROVED** [review]
Ok, this looks good. 

I could it could be possible to drop some packages, but I'd need to review how we use it in the infra first.

**Pull request merged**
